name: Metrics
on:
  schedule: [{cron: "0 20 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.Lang_Metrics_Token }}
          user: omaratabany
          template: classic
          base: topics, metadata
          config_timezone: Asia/Dubai
          
          filename: lang_metrics.svg
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_analysis_timeout: 60

          # plugin_languages_ignored: Jupyter Notebook
          plugin_languages_categories: programming
          plugin_languages_colors: rainbow
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_followup: yes
          plugin_followup_indepth: yes
          plugins_errors_fatal: yes 
